[module]
  [module.hugoVersion]
    min = "0.81.0"
    max = "0.84.2"
	
baseURL = "https://www.example.com"
title = "My Digital Garden"
theme = "hugo-digital-garden-theme"
themesdir = "../../"
copyright = "Nigalya Ponya ©"
languageCode = "en-us"

[params]
  name = "Michael Kuchenko"
  description = "Здесь собираю свои статьи и проекты."
  initials = "MK"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "#"
    icon = "fab fa-github"

  [[params.social]]
    name = "Medium" 
    link = "#"
    icon = "fab fa-medium-m"

  [[params.social]]
    name = "LinkedIn"
    link = "#"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Записи"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Проекты"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Библиотека"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "Обо мне"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'